name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./tp1
        file: ./tp1/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

    - name: Deploy to VM via SSH
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: 20.86.55.5
            username: ubuntu
            password: Supermotdepasse!42
            port: 22
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
              docker stop my-app || true
              docker rm my-app || true
              docker run -d --name my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
